- type: antag
  id: Mindflayer
  name: roles-antag-mindflayer-name
  antagonist: true
  setPreference: true
  objective: roles-antag-mindflayer-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
  guides: [ Mindflayer ]
